name: Deploy to repo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up NodeJS LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config --global user.name 'listkr-bot'
          git config --global user.email '176363712+listkr-bot@users.noreply.github.com'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
  release:
    name: Create a Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up NodeJS LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create a Release
        uses: List-KR/semver-release@2.2.0
    needs: [build]
  jsdelivrpurge:
    name: Purge jsDelivr cache
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: Set up NodeJS LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run jsDelivr-Purge
        uses: List-KR/jsdelivr-purge@5.6.0
    needs: [build, release]
